[package]
name = "desktop"
version = "0.0.33"
authors = ["you"]
edition = "2021"
description = "Hyprnote Desktop App"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "hyprnote_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
sim-english-1 = ["hypr-data"]
sim-korean-1 = ["hypr-data"]

[build-dependencies]
tauri-build = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
tauri-plugin-apple-calendar = { path = "../../../plugins/apple-calendar" }

[dependencies]
hypr-data = { workspace = true, optional = true }
hypr-db-core = { workspace = true }
hypr-db-user = { workspace = true }
hypr-turso = { workspace = true }

tauri-plugin-analytics = { workspace = true }
tauri-plugin-auth = { workspace = true }
tauri-plugin-connector = { workspace = true }
tauri-plugin-db = { workspace = true }
tauri-plugin-flags = { workspace = true }
tauri-plugin-listener = { workspace = true }
tauri-plugin-local-llm = { workspace = true }
tauri-plugin-local-stt = { workspace = true }
tauri-plugin-misc = { workspace = true }
tauri-plugin-notification = { workspace = true }
tauri-plugin-opener = { workspace = true }
tauri-plugin-sfx = { workspace = true }
tauri-plugin-sse = { workspace = true }
tauri-plugin-store2 = { workspace = true }
tauri-plugin-template = { workspace = true }
tauri-plugin-tray = { workspace = true }
tauri-plugin-windows = { workspace = true }
tauri-plugin-gitee-ai = { workspace = true }

tauri = { workspace = true, features = ["specta", "macos-private-api"] }
tauri-plugin-autostart = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-decorum = { workspace = true }
tauri-plugin-deep-link = { workspace = true }
tauri-plugin-dialog = { workspace = true }
tauri-plugin-fs = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-http = { workspace = true }
tauri-plugin-os = "2"
tauri-plugin-prevent-default = { version = "1.2", features = ["unstable-windows"] }
tauri-plugin-process = "2"
tauri-plugin-sentry = { version = "0.4.1", features = ["tracing"] }
tauri-plugin-shell = "2"
tauri-plugin-single-instance = { version = "2", features = ["deep-link"] }
tauri-plugin-store = { workspace = true }
tauri-plugin-updater = "2"
tauri-plugin-window-state = "2"

tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "chrono"] }

specta = { workspace = true }
specta-typescript = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tauri-specta = { workspace = true, features = ["derive", "typescript"] }

anyhow = { workspace = true }
thiserror = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

bytes = { workspace = true }
chrono = { workspace = true }
codes-iso-639 = { workspace = true }
dotenvy_macro = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

futures-util = { workspace = true }
reqwest = { workspace = true, features = ["json", "stream"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tokio-stream = { workspace = true }

hound = { workspace = true }
